### PR TITLE
Add in TVOS, Update to Swift 4, fix some regexes

### PR DESCRIPTION
**Pull request by jvanmetre**
Hey Chris, these are a bunch of edits I made, feel free to incorporate any/all of them, but I figured I should contribute them back to the main repo.

### CODE REVIEW

**Comment by chrisdhaan** [comment]
Hey James. Thanks for this! Funny enough, I just pushed an update tonight for new platforms. But the regex fixes are super helpful. I'll definitely take a look through this an implement as much as I can.

**Comment by tklucher** [comment]
I am really liking the regex fixes. Been testing them the last 48 hours and I feel like the result of the parse has less overall whitespace between things. It also treats complex links a lot better. I was able to add most of @jvanmetre fixes while keeping @chrisdhaan Swift 4 changes and TVOS changes.

Let me know if you would like a pull request from [this](https://github.com/visvateam/CDMarkdownKit/commits/master). The main reason I didn't was I butchered Parse Image so that I could pass the URL along to our image cacheing system. I could probably make a separate branch without my image change if it would help. :)

**Comment by chrisdhaan** [comment]
@tklucher I've got changes (including the regexes) that I'm merging in soon. Have been super busy. Hoping I can get something out tomorrow.

**Comment by chrisdhaan** [comment]
@tklucher I'll be pushing up a build tonight that includes local image store for `CDMarkdownImage` and the updated regexes. I'm still reviewing some of the other attribute parsing from this PR. After I'm done reviewing, I want to implement link selection in `CDMarkdownLabel`, will update to Swift 4, and then release `1.0.0`. Hopefully `1.0.0` is out by end of February.

**Comment by tklucher** [comment]
@chrisdhaan That is really awesome. I can’t wait to give it a try.

**Comment by tklucher** [comment]
@chrisdhaan  I took a closer look at the paragraph styles and I think if they are included for the full parsed document they should be exposed on the Parser class and was thinking that [number of lines before and after](https://github.com/visvateam/CDMarkdownKit/blob/master/Source/CDMarkdownParser.swift) seems to work well. 

I have also been trying to make block quotes look better and in [my implementation](https://github.com/visvateam/CDMarkdownKit/blob/master/Source/CDMarkdownQuote.swift) I like the look of an indent so I gave it a try. I think if this ever gets put in it would have to be tied into level in some way and have level be a multiplier of the first level indent value. I just did a kludge to get what I wanted but if we decide to support multiple levels in the future I might take another look. I also might need to set the after paragraph spacing in a different way because if you make the size on the quote text larder you get more space after the paragraph, in this current code. Not sure what the best solution for this will be but I plan to keep improving it on my end and if I come up with anything that looks promising I will pull request it back in.

Also [here is some code](https://gist.github.com/tklucher/63244f1eb187f1ab5303321d69e20505) I have been using for my own markdown labels that are tappable for hyperlinks. I sorta put this together from things I have found. The main reason I have not used the label in CDMarkdownKit is that I currently use XIB files for where the markdown is displayed and I read in the readme about the issues with storyboards. I plan to take a look at that as well when I have some time as I would like the rounding corners for the code and syntax blocks in the future. I currently handle the tap recognizer for this code in the view it is attached to but I think adding some sort of optional closure would allow you to package the gesture recognizer in with the Label subclass. Something like this maybe?

```
public var linkTapped: ((URL) -> Void)?

let recognizer = UITapGestureRecognizer(target: self, action: #selector(userTappedOnBody))
lblBody.addGestureRecognizer(recognizer)

    @objc fileprivate func userTappedOnBody(_ sender: UITapGestureRecognizer) {
        if let urlTapped = lblBody.userDidTap(withRecognizer: sender) {
            self.linkTapped?(urlTapped)
        }
    }

```

**Comment by chrisdhaan** [comment]
@tklucher exposing paragraph styles in the Parser object is a good idea. Can you document your comment as an `Issue`? I'm working on finishing UILabel functionality and some of the last work in this PR and will then be closing this out. I don't want to lose your feature request.

**Comment by WillBishop** [comment]
This completely breaks all watchOS support

**Comment by tklucher** [comment]
@WillBishop That is correct this repo was forked from the main project before that support was added. I did not know you needed watch support when I originally recommended it, as that request was not in your original issue. At this point you only have three options. 

1. Wait for the update.
2. Fork the current and do a Swift 4 update yourself based on the changes in other forks.
3. Build on Swift 3.x

Sorry but those are the only options at this point.

**Comment by chrisdhaan** [comment]
@WillBishop if it can wait until Sunday evening. I will have an update out by then which should resolve your issues.

**Comment by WillBishop** [comment]
Oh please it’s no trouble. I have a local swift 4 fork anyway, if you’d prefer to drop support for it I totally understand (though I prefer if you didn’t)

Do whatever works best for you

**Comment by chrisdhaan** [comment]
Everything from this PR has been implemented. Closing.

**Pull request closed without merging**
