### PR TITLE
Made the framework compile on Xcode 11.4

### PR DESCRIPTION
**Pull request by raphaelcruzeiro**
### Issue Link 
#21 

### Goals :soccer:
Updated a `switch` statement to handle additional `UITouch` cases and updated the `Package.swift` to use the 5.2 toolchain

### CODE REVIEW

**Comment by matiaz** [comment]
hey man, thanks for the PR, wondering if they will review this PR soon or if this repo still been supported by the owner, if not I think I should fix it on my side too

**Comment by matiaz** [comment]
@chrisdhaan dude ?

**Comment by MatyashDen** [comment]
@matiaz @raphaelcruzeiro @ismyhc @FelixII @chrisdhaan  don't know when this PR will be merged?

**Comment by chrisdhaan** [comment]
@raphaelcruzeiro @matiaz @MatyashDen addressed in #24. Closing this PR as duplicate. Thanks for pointing this out.

**Pull request closed without merging**
