### PR TITLE
#26. Add possibility to use multiple \n in a row.

### PR DESCRIPTION
**Pull request by MatyashDen**
Add possibility to use multiple \n in a row

### CODE REVIEW

**Comment by MatyashDen** [comment]
@chrisdhaan would be great if you could review this PR

**Comment by MatyashDen** [comment]
@chrisdhaan would be great if you could review this PR

**Comment by delarge77** [comment]
@MatyashDen Good you did it ! Unfortunately no one approved it yet !

**Comment by chrisdhaan** [comment]
@MatyashDen can you send me an example string that this fixes for you so I can also test the changes prior to merging?

**Comment by MatyashDen** [comment]
@chrisdhaan 
Here it is:
`Hello \n\n World`
By default library changed string to
`Hello \n World`
But after my PR with `shouldSquashEndlines ` equal to true it will do nothing with this string

**Review by tarrouye — APPROVED** [review]
We did the same in our fork. I think it's worth having as an option, and doesn't break anything.

**Comment by kimrypstraHE** [comment]
Hi @chrisdhaan, and chance of a review for this PR? Let me know if I can help out in any way 👍

**Comment by chrisdhaan** [comment]
@MatyashDen @delarge77 @tarrouye @kimrypstraHE sorry for the delay in getting this functionality into the project. Added with PR #38 and available in version `2.3.0`

**Comment by kimrypstraHE** [comment]
@chrisdhaan That's great, thank you!

**Pull request closed without merging**
